Plan-You/PlanU-FE

- .gitignore
> close #1 
> - gitignore파일에 .env 파일 추가
> chore: gitignore파일에 .env 파일 추가

- src/pages/ModifyMyAccountPage/page/index.tsx
> close #5 
> - 페이지 폴더 내 회원 정보 수정 페이지 폴더 및 파일 추가
> chore: 회원 정보 수정 페이지 추가

- src/api/fetcher.ts
- src/vite-env.d.ts
- vite.config.ts
> close #8 
> 백엔드 api url 연결 로직 작성
> 루트 경로에 .env파일 새로 만들어서 디코에 보낸 백엔드 api url 저장해주세요
> chore: 백엔드 api url 추가 및 설정

- src/layout/Layout.tsx
> close #14 
> - padding 추가
> -
> style: padding 추가

- src/pages/CreateGroupPage/components/ImageUploader.tsx
> close #50 
> - ImageUploader 컴포넌트에 이미지 유효성 검사 로직 추가
> - jpg, jpeg, png 형식, 5MB 이하 이미지만 업로드 가능
> Feat: ImageUploader 컴포넌트에 이미지 유효성 검사 로직 추가

- .gitignore
- src/api/apiRoutes.ts
- src/api/user/postUserInformation.ts
- src/components/modals/InviteModal.tsx
- src/components/modals/Modal.stories.tsx
- src/components/modals/inviteModal.module.scss
- src/pages/CreateGroupPage/components/GroupNameInput.tsx
- src/pages/CreateGroupPage/components/ImageUploader.tsx
- src/pages/CreateGroupPage/page/index.tsx
- src/pages/RegisterAccountPage/components/DatePicker.tsx
- src/pages/RegisterAccountPage/page/index.tsx
- src/types/post.d.ts
> close #52 
> 1. 초대 수락 모달 퍼블리싱 작업
> 2. 무조건 body의 중앙에 뜨도록 하기 위한 ReactDOM의 createPortal 사용
> 3. 초대 수락 모달 스토리북 작성
> Style: 초대 모달 퍼블리싱 작업

- .gitignore
- src/api/apiRoutes.ts
- src/api/user/postUserInformation.ts
- src/pages/CreateGroupPage/components/GroupNameInput.tsx
- src/pages/CreateGroupPage/components/ImageUploader.tsx
- src/pages/CreateGroupPage/page/index.tsx
- src/pages/RegisterAccountPage/components/DatePicker.tsx
- src/pages/RegisterAccountPage/page/index.tsx
- src/types/post.d.ts
> close #46 
> 1. 회원정보 등록 api 연동 로직 작성 완료
> 2. 회원정보등록 api에서 사용되는 요청 데이터 타입 types/post.d.ts에 정의
> -
> 회원정보등록 api 연동 여부는 수현님이 담당하시는 로그인, 회원가입 페이지 api 연동 완료되면 그때 확인할게여
> Feat: 회원 정보 등록 페이지 api 연동로직 작성 및 생년월일 유효성 검사 로직 작성

- src/api/apiRoutes.ts
- src/api/fetcher.ts
- src/api/user/getUserInfo.ts
- src/api/user/postUserInformation.ts
- src/pages/RegisterAccountPage/page/index.tsx
> close #62 
> 1. 회원정보등록 api 연동 확인
> 2. 회원정보조회 api 연동 로직 작성 및 확인
> 1. 회원정보등록 api 연동 로직에서 일반 fetch로 로직 수정
> 2. 회원정보등록 api 연동 로직에서 request data 필드 값 백엔드 수정에 따른 수정
> Feat: 회원정보조회 api 연동 로직 작성 및 회원정보등록, 조회 api 연동 확인

- src/api/fetcher.ts
- src/api/user/postLogin.ts
- src/api/user/postReissue.ts
- src/api/user/postUserInformation.ts
- src/pages/LoginPage/page/index.tsx
- src/pages/RegisterPage/page/index.tsx
> close #69 
> 1. fetcher에서 에러 받았을때 백엔드에서 보내주는 resultMsg만 따로 빼내서 throw new error로 에러 핸들링 해줌
> 2. 에러 메시지 화면에 띄울때 onError: (error) => { alert(error.message); } 이렇게만 작성하면 백엔드에서 보내주는 resultMsg에 담긴 내용 보여줄수 있음
> -
> feat: 백엔드에서 보내주는 에러(resultMsg)만 따로 빼는 에러 핸들링 로직 작성

- src/components/buttons/Button.stories.tsx
- src/components/buttons/FindButton.tsx
- src/components/buttons/find.module.scss
- src/components/inputBoxes/LoginInput.tsx
- src/pages/FindPage/components/FindInput.stories.tsx
- src/pages/FindPage/components/FindInput.tsx
- src/pages/FindPage/components/FindTab.stories.tsx
- src/pages/FindPage/components/FindTypeTab.tsx
- src/pages/FindPage/components/InputItem.tsx
- src/pages/FindPage/components/Tab.module.scss
- src/pages/FindPage/components/findInput.module.scss
- src/pages/FindPage/components/inputItem.module.scss
- src/pages/FindPage/page/find.module.scss
- src/pages/FindPage/page/index.tsx
- src/types/form.d.ts
- src/types/post.d.ts
> Style: 아이디/비밀번호 찾기 페이지 퍼블리싱

- src/routes/CommonRoute.tsx
- src/routes/ProtectedRoute.tsx
> close #76 
> - 로그인 상태 여부 검사하는 로직에서 api 호출 결과가 아닌 로컬스토리지의 액세스토큰 값 여부로 수정
> hotfix: 로그인 상태 여부 검사하는 로직 수정

- src/assets/Icons/Icon_add_circle.svg
- src/pages/CreateGroupPage/page/index.tsx
- src/pages/GroupListPage/components/GroupItem.tsx
- src/pages/GroupListPage/components/InvitateItem.tsx
- src/pages/GroupListPage/components/InviteItem.tsx
- src/pages/GroupListPage/components/groupItem.module.scss
- src/pages/GroupListPage/page/groupList.module.scss
- src/pages/GroupListPage/page/index.tsx
> ex) #79 
> 그룹 목록 페이지 퍼블리싱 간단히
> -
> style: 그룹 목록 페이지 퍼블리싱

- src/api/friend/getFriendList.ts
- src/pages/FriendManagementPage/components/MemberCard.tsx
- src/pages/MyPage/components/ButtonSection.tsx
- src/pages/MyPage/components/ProfileSection.tsx
- src/pages/MyPage/components/profileSection.module.scss
- src/pages/MyPage/page/index.tsx
- src/pages/MyPage/page/myPage.module.scss
- src/pages/Mypage/components/ButtonSection.tsx
- src/pages/Mypage/components/ProfileSection.tsx
- src/pages/Mypage/components/profileSection.module.scss
> feat: 마이페이지 api 연동

- src/api/friend/deleteCancelRequestFriend.ts
- src/api/friend/deleteDeleteFriends.ts
- src/api/friend/deleteRejectRequestFriend.ts
- src/api/friend/getFriendList.ts
- src/api/friend/getReceiveFriendList.ts
- src/api/friend/getRequestFriendList.ts
- src/api/friend/postAcceptRequestFriend.ts
- src/api/friend/postRequestFriend.ts
- src/pages/FriendManagementPage/components/IDInput.tsx
- src/pages/FriendManagementPage/components/MemberCard.tsx
- src/pages/FriendManagementPage/page/friendManagementPage.module.scss
- src/pages/FriendManagementPage/page/index.tsx
- src/types/friend.d.ts
> Feat: 마이페이지-친구관리 api 연동

- src/App.tsx
- src/api/group/getGroupCalendarSchedules.ts
- src/components/calendarPage/EventCard.tsx
- src/components/calendarPage/eventCard.module.scss
- src/components/headers/CalendarHeader.tsx
- src/components/headers/calendarHeader.module.scss
- src/pages/GroupCalendarPage/page/groupCalendarPage.module.scss
- src/pages/GroupCalendarPage/page/index.tsx
- src/pages/GroupPage/components/GroupScheduleCalendar.tsx
- src/pages/GroupPage/page/index.tsx
- src/pages/MyCalendarPage/page/index.tsx
- src/pages/MyCalendarPage/page/myCalendarPage.module.scss
- src/pages/MyPage/page/myPage.module.scss
- src/types/calendar.d.ts
- src/types/get.d.ts
- src/types/group.d.ts
> close #149 
> - 그룹 달력 총 일정 조회 api endpoint 수정에 따른 프론트로직 및 데이터타입 수정
> Hotfix: 그룹 달력 총 일정 조회 api endpoint 수정에 따른 프론트로직 및 데이터타입 수정

- src/App.tsx
- src/api/calendar/getMyCalendarCheckEvents.ts
- src/api/calendar/getMyScheduleList.ts
- src/pages/MyCalendarPage/page/index.tsx
- src/types/calendar.d.ts
#174 
나의 달력 페이지 api연동
개인 달력 일정 유무 조회 및 일정 조회
- 테스트
> feat: 나의 달력 페이지 api 연동

- src/api/apiRoutes.ts
- src/pages/LocationSharingPage/components/GroupMemberItem.tsx
- src/pages/LocationSharingPage/components/groupMemberItem.module.scss
- src/pages/LocationSharingPage/page/index.tsx
- src/pages/LocationSharingPage/page/locationSharing.module.scss
- src/types/locationInfo.d.ts
> 
> - 위치공유 페이지에서 참여자 목록의 참여자 클릭하면 border가 두꺼워지고 보라색으로 강조되도록 스타일 적용
> style: 위치공유 페이지에서 참여자 목록의 참여자 클릭하면 border가 두꺼워지고 보라색으로 강조되도록 스타일 적용

- src/api/apiRoutes.ts
- src/api/friend/getRecommendedFriendList.ts
- src/pages/FriendManagementPage/page/friendManagementPage.module.scss
- src/pages/FriendManagementPage/page/index.tsx
- src/types/friend.d.ts
#204 
- 마이페이지 - 친구관리 - 추천친구 api 연동
- apiRoutes 경로 추가
> Feat: 마이페이지 - 추천 친구 api 연동

- vite.config.ts
> fix: .pem 파일 production 환경에서는 undefined로 반영되도록 수정

- src/pages/ChattingPage/page/index.tsx
> fix: 빌드 오류 수정

- src/components/calendar/Calendar.tsx
> fix: 빌드 오류 수정 import 파일 철자 수정

- src/pages/EditProfilePage/components/InlineEditableProfileItemWithButton.tsx
> fix: build에러 수정 - import 철자 수정

- src/components/calendar/Calendar.tsx
- src/pages/EditProfilePage/components/InlineEditableProfileItemWithButton.tsx
> Deploy: build에러 수정 - import 철자 수정

- src/App.tsx
- src/components/createSchedule/ChangeColorBox.tsx
- src/components/createSchedule/ColorBox.tsx
- src/components/createSchedule/Inputs.module.scss
- src/components/createSchedule/MemberBox.tsx
- src/components/createSchedule/changeColorBox.module.scss
- src/components/scheduleDetail/Boxes.module.scss
- src/components/scheduleDetail/LocationBox.tsx
- src/pages/CreateSchedulePage/page/index.tsx
- src/pages/EditSchedulePage/page/index.tsx
- src/pages/GroupScheduleDetailPage/page/index.tsx
- src/store/useScheduleStore.ts
> close #222 
> 1. 일정 생성하기 및 수정하기 색상 추가 모달 퍼블리싱
> 2. 그룹 일정 생성 페이지에서의 참석자 확인 버튼 리퍼블리싱
> Style: 일정 생성하기 및 수정하기 색상 추가 모달 퍼블리싱 및 그룹 일정 생성 페이지에서의 참석자 확인 버튼 리퍼블리싱

- src/components/scheduleDetail/LocationBox.tsx
- src/pages/ChatListPage/components/ChatItem.tsx
- src/pages/EditSchedulePage/page/index.tsx
- src/pages/MyPage/components/ButtonSection.tsx
- src/pages/MyPage/components/ProfileSection.tsx
- src/pages/MyPage/components/buttonSection.module.scss
- src/pages/MyPage/components/profileSection.module.scss
> ex) #이슈번호
> - 사라진 myPage component 파일 복구
> - edit page location 컴포넌트 props 넘겨주기
> - build시 사용 안 하는 코드 삭제
> -
> Hotfix: build 에러 수정 및 사라진 파일 추가 

- src/components/createSchedule/DatePicker.tsx
- src/components/createSchedule/TimePicker.tsx
- src/pages/ChattingPage/components/BottomMenuBox.tsx
- src/pages/CreateGroupPage/components/ImageUploader.tsx
- src/pages/CreateGroupPage/page/index.tsx
- src/pages/EditProfilePage/page/index.tsx
- src/pages/FindPage/page/index.tsx
- src/pages/LoginPage/page/index.tsx
- src/pages/RegisterAccountPage/page/index.tsx
- src/pages/RegisterPage/page/index.tsx
> ex) #이슈번호
> - 
> 1. alert알림 toast알림으로 일괄 수정
> fix: alert알림 toast알림으로 일괄 수정

- src/App.tsx
- src/components/createSchedule/LocationBox.tsx
- src/components/createSchedule/MemberBox.tsx
- src/pages/ChattingPage/components/ChatBubble.tsx
- src/pages/ChattingPage/components/chatBubble.module.scss
- src/pages/ChattingPage/components/chattingHeader.module.scss
- src/pages/ChattingPage/page/chatPage.module.scss
- src/pages/ChattingPage/page/index.tsx
- src/pages/CreateSchedulePage/page/index.tsx
- src/pages/EditSchedulePage/page/editSchedule.module.scss
- src/pages/EditSchedulePage/page/index.tsx
- src/pages/GroupScheduleDetailPage/page/index.tsx
- src/store/useScheduleStore.ts
> 
> - 내일정 수정시 그룹 일정 수정 api 호출되는 문제 해결
> - 일정 수정 페이지에 취소 버튼 두기, 수정시 위치 데이터 사라지는 것 해결
> - 일정 생성시 생성자 이름 한 번 더 들어가는 거 수정
> - 채팅방 입장시 빈 버블 뜨는 현상 수정
> - 채팅 ui 수정 ( 프로필 이미지 위 이름, 채팅방과 사진 간격 넓히기)
> -
> Fix: 1차 QA 후 기능상 오류 수정

- src/pages/EditProfilePage/page/index.tsx
- src/pages/FriendManagementPage/components/MemberCard.tsx
- src/pages/FriendManagementPage/components/memberCard.module.scss
- src/pages/FriendManagementPage/page/friendManagementPage.module.scss
- src/pages/FriendManagementPage/page/index.tsx
#234 
- 프로필 이미지 수정 안 되는 문제
- 추천 친구에서 친구 요청이 안 보내짐 
- 친구 목록 프로필 둥글게 보이도록 수정  
- 추천 친구 요청 시 요청 중/요청 취소 버튼 반영되도록 수정
- 친구 목록에서 수정하기 버튼으로 인해 일부 카드 가려지는 문제 수정
> Fix: [1차 QA] 친구 및 마이페이지 관련 UI/기능 수정

- src/components/createSchedule/ChangeColorBox.tsx
- src/components/scheduleDetail/LocationBox.tsx
- src/pages/GroupMemberPage/page/groupMember.module.scss
- src/pages/GroupScheduleDetailPage/page/index.tsx
- src/pages/LocationSharingPage/page/index.tsx
- src/pages/SelectLocationPage/page/index.tsx
> close #239 
> 1. 위치 공유 페이지에서 자신의 위치로 돌아오는 에러 수정(혼자 테스트 불가)
> 2. 참석자가 아닌 그룹원이 그룹 일정의 위치 현황 버튼을 누르면 공유 페이지 들어가지 못하도록 막는 로직 작성
> 3. LocationBox에 React.memo걸어줌
> 1. 멤버 목록 컴포넌트 높이 수정
> 1. 위치 공유 페이지에서 자신의 위치로 돌아오는 에러 수정하긴 했는데 혼자 테스트가 어려워서 일단 배포하고 테스트 해봐야할 것 같아요
> Fix: 2차 qa 오류 수정
